### ISSUE TITLE
Update Respond JS to latest version

### ISSUE THREAD

**Issue by coliff** [corysimmons/ie-love#5]
Looks like Respond JS 1.4.0 is included - can it be update to 1.4.2?

REF: https://github.com/scottjehl/Respond/blob/master/dest/respond.min.js

**Comment by corysimmons** [comment]
Good eye. I've got this setup as a build tool that will download a fresh Bower copy, but the `respond.src.js` it keeps getting is 1.4.0... :[

I suspect someone there updated some stuff and didn't do a new tag.

I've included the minified version which purports to be 1.4.2. /shrug
